# Generated by Django 4.2.23 on 2025-08-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cur_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('cur_txt_nombre', models.CharField(max_length=191)),
                ('cur_txt_descripcion', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('exa_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('exa_txt_titulo', models.CharField(max_length=191)),
                ('cur_int_id', models.ForeignKey(db_column='cur_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='IntentoExamen',
            fields=[
                ('int_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('int_flt_puntaje', models.FloatField()),
                ('int_dat_fecha', models.DateTimeField(auto_now_add=True)),
                ('exa_int_id', models.ForeignKey(db_column='exa_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('niv_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('niv_txt_nombre', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pre_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_txt_texto', models.CharField(max_length=191)),
                ('cur_int_id', models.ForeignKey(db_column='cur_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.curso')),
                ('niv_int_id', models.ForeignKey(db_column='niv_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('res_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_txt_texto', models.CharField(max_length=191)),
                ('res_bol_es_correcta', models.BooleanField()),
                ('pre_int_id', models.ForeignKey(db_column='pre_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_txt_nombre', models.CharField(max_length=191)),
                ('rol_txt_descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_txt_nombre', models.CharField(max_length=191)),
                ('usu_txt_apellidos', models.CharField(max_length=191)),
                ('usu_txt_email', models.EmailField(max_length=191, unique=True)),
                ('usu_txt_password', models.CharField(max_length=191)),
                ('usu_txt_colegio', models.CharField(max_length=191)),
                ('usu_txt_grado', models.CharField(max_length=191)),
                ('usu_dat_fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol_int_id', models.ForeignKey(db_column='rol_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.rol')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('run_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('int_int_id', models.ForeignKey(db_column='int_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.intentoexamen')),
                ('pre_int_id', models.ForeignKey(db_column='pre_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.pregunta')),
                ('res_int_id', models.ForeignKey(db_column='res_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.respuesta')),
                ('usu_int_id', models.ForeignKey(db_column='usu_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('lec_int_id', models.AutoField(primary_key=True, serialize=False)),
                ('lec_txt_titulo', models.CharField(max_length=191)),
                ('cur_int_id', models.ForeignKey(db_column='cur_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.curso')),
                ('niv_int_id', models.ForeignKey(db_column='niv_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.nivel')),
            ],
        ),
        migrations.AddField(
            model_name='intentoexamen',
            name='usu_int_id',
            field=models.ForeignKey(db_column='usu_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.usuario'),
        ),
        migrations.AddField(
            model_name='examen',
            name='niv_int_id',
            field=models.ForeignKey(db_column='niv_int_id', on_delete=django.db.models.deletion.RESTRICT, to='api.nivel'),
        ),
    ]
